import type { Day } from "@/core/types";
type DaySeed = Omit<Day, "id">;

/**
 * 24 days. Loose by design — a title and a few lines of intent. Travel days link
 * a journey; day-trip days carry getting-there / back / what-to-do. Rearrange
 * freely on the Plan tab; add your own places from Google Maps.
 */
export const days: DaySeed[] = [
  {
    date: "2026-10-21",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    journeyId: "j-arrival",
    title: "Arrival",
    notes:
      "In via Beijing on the red-eye. Monorail to Hamamatsuchō, drop the bags, stay upright until a normal bedtime. Slow lunch, a flat walk, easy dinner nearby. Activate the eSIM, top up Suica.",
  },
  {
    date: "2026-10-22",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "Old Tokyo",
    notes: "Asakusa and the low city — Sensō-ji before the crowds, Kappabashi, the Sumida riverside. Gentle first full day.",
  },
  {
    date: "2026-10-23",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "West side",
    notes: "Meiji Jingū, Harajuku, Omotesandō → Shibuya. Shimokitazawa for dinner and record shops.",
  },
  {
    date: "2026-10-24",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "East side & coffee",
    notes: "Kiyosumi gardens, a coffee crawl through Kiyosumi / Kuramae / Nakameguro. Laundry tonight before the mountains.",
  },
  {
    date: "2026-10-25",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "Open day",
    notes: "Flex — a museum, backstreets, more coffee, or nothing. Tonight: split the luggage (overnight bag vs big cases for Yamato tomorrow).",
  },
  {
    date: "2026-10-26",
    legId: "kawaguchiko",
    hotelId: "hotel-yamitsuki",
    journeyId: "j-tokyo-kawaguchiko",
    title: "To the lake",
    notes: "Hand the big cases to Yamato, Fuji Excursion from Shinjuku. Afternoon by the water — Ōishi Park, the lakeshore path. Onsen, then dinner.",
  },
  {
    date: "2026-10-27",
    legId: "kawaguchiko",
    hotelId: "hotel-yamitsuki",
    title: "Fuji day",
    notes: "Chūreitō Pagoda at first light (clearest air, ~400 steps). Kachi Kachi ropeway, a slow lake loop. Last onsen; repack for Kyoto.",
  },
  {
    date: "2026-10-28",
    legId: "kyoto",
    hotelId: "hotel-icy",
    journeyId: "j-kawaguchiko-kyoto",
    title: "To Kyoto",
    notes: "Mishima Liner bus, then the Hikari to Kyoto. Check in to ICY, confirm the luggage arrived, find the konbini. Nishiki or Pontochō for dinner.",
  },
  {
    date: "2026-10-29",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Southern Higashiyama",
    notes: "Kiyomizu-dera at opening, down the Sannenzaka / Ninenzaka lanes, Kōdai-ji garden, Maruyama Park, Yasaka, Gion, the Shirakawa canal late afternoon.",
    getThere: "City bus 100 / 206 to Gojō-zaka or Kiyomizu-michi (~15 min from Kyoto Station), or Keihan to Kiyomizu-Gojō and walk up.",
    getBack: "Keihan from Gion-Shijō, or bus 206 from Gion. Walk down to Sanjō for dinner.",
    toDo: ["Kiyomizu-dera — from 06:00, go first", "Sannenzaka & Ninenzaka lanes", "Kōdai-ji (garden; night illumination in Nov)", "Gion & Shirakawa canal — late afternoon"],
    lastTrainBack: "In the city — buses run late; Keihan Gion-Shijō until ~23:30.",
  },
  {
    date: "2026-10-30",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Fushimi Inari & Tōfuku-ji",
    notes: "Torii gates before 8 (up to the Yotsutsuji viewpoint). Tōfuku-ji's maple ravine as it turns. Coffee at Weekenders, dinner downtown.",
  },
  {
    date: "2026-10-31",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Arashiyama",
    notes: "Bamboo grove at opening, Tenryū-ji garden, the Sagano scenic train if seats are free.",
    getThere: "JR San-in line to Saga-Arashiyama (~15 min from Kyoto), or Randen tram from the centre.",
    getBack: "JR from Saga-Arashiyama, last trains ~23:00.",
    toDo: ["Bamboo grove — at opening or it's shoulder-to-shoulder", "Tenryū-ji garden", "Sagano Romantic Train (book ahead in foliage season)", "Katsura river & Togetsukyō bridge"],
    lastTrainBack: "JR to Kyoto until ~23:00.",
  },
  {
    date: "2026-11-01",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Central Kyoto",
    notes: "Slower city day — Nijō Castle, Nishiki Market, the coffee list, Pokémon Center at Takashimaya.",
  },
  {
    date: "2026-11-02",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Nara",
    notes: "Tōdai-ji's Great Buddha, the deer, Kasuga's lantern approach, the quiet moss of Isuien.",
    getThere: "Kintetsu Limited Express, Kyoto → Kintetsu-Nara, ~35 min (reserved, ~¥1,160). Or JR Miyakoji Rapid, ~45 min, no reservation.",
    getBack: "Reserve the Kintetsu return on the way out. Or JR Rapid from JR Nara.",
    toDo: ["Tōdai-ji Daibutsuden — opens 07:30 in autumn", "Nara Park & Nandaimon", "Kasuga Taisha — the approach path is the best part", "Isuien Garden — small, ticketed, near-empty"],
    lastTrainBack: "Kintetsu / JR to Kyoto until ~23:00.",
  },
  {
    date: "2026-11-03",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Culture Day (holiday)",
    notes: "National holiday — big sights will be packed. Good day for a museum, the Kyoto Railway Museum, or the quieter west of the city.",
  },
  {
    date: "2026-11-04",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Uji",
    notes: "Byōdō-in's Phoenix Hall (the ¥10-coin building), the fast green river, the two UNESCO shrines, the best matcha of the trip.",
    getThere: "JR Nara Line Rapid, Kyoto → Uji, ~20 min, ~¥240. Or the Keihan Uji line via Chūshojima (more scenic).",
    getBack: "JR from Uji, or Keihan from Keihan-Uji (closer to Byōdō-in).",
    toDo: ["Byōdō-in & Phoenix Hall — timed interior entry, book on arrival", "Uji Bridge & Tō-no-shima island", "Ujigami Shrine — 10 min across the river", "Matcha: Nakamura Tōkichi or Itoh Kyuemon"],
    lastTrainBack: "JR Nara line to Kyoto until ~23:00.",
  },
  {
    date: "2026-11-05",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Ōhara",
    notes: "Bus north to the moss gardens of Sanzen-in — foliage peaks here first. Hōsen-in for tea in front of the framed-garden view, then the quiet walk to Jakkō-in.",
    getThere: "Kyoto Bus 17 from Kyoto Station or Demachiyanagi to Ōhara, ~60 min.",
    getBack: "Same bus. The last one leaves Ōhara around 18:20 — check the timetable on arrival, it thins out.",
    toDo: ["Sanzen-in — the moss garden with the little Jizō figures", "Hōsen-in — sit for tea", "Jakkō-in — 15 min walk, quiet", "Soba near the Sanzen-in approach (closes ~16:00)"],
    lastTrainBack: "No train — last Kyoto Bus back ~18:20.",
  },
  {
    date: "2026-11-06",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Northern Higashiyama",
    notes: "Ginkaku-ji, the Philosopher's Path, Eikan-dō for its famous maples — walk south all afternoon.",
  },
  {
    date: "2026-11-07",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Kurama → Kibune",
    notes: "The little mountain railway, the temple-to-shrine hike over the ridge, kaiseki by the river. Real walking shoes; start by 10:00, daylight is short.",
    getThere: "Eizan line from Demachiyanagi to Kurama, ~30 min.",
    getBack: "Eizan line from Kibune-guchi. Runs until ~21:00, but the trail is unlit and closes at dusk — be off the mountain by 16:00 (sunset ~16:45).",
    toDo: ["Kurama-dera — cable car or walk up", "The ridge trail to Kibune (~1 hr, roots and steps)", "Kifune Shrine", "Book a Kibune lunch (kawadoko in season)"],
    lastTrainBack: "Eizan line ~21:00 — but be off the mountain by 16:00.",
  },
  {
    date: "2026-11-08",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTrip: true,
    title: "Osaka",
    notes: "Kuromon market for breakfast, the castle grounds, Dōtonbori and Shinsekai after dark. Loud, fun, a change of pace. Go hungry, cash for stalls.",
    getThere: "JR Special Rapid, Kyoto → Ōsaka, ~29 min, ~¥580. Or Hankyu Limited Express Kawaramachi → Umeda.",
    getBack: "JR Special Rapid from Ōsaka Station, or Hankyu from Umeda.",
    toDo: ["Kuromon Ichiba market — before 11:00", "Osaka Castle & park — grounds, skip the keep queue", "Dōtonbori & Hōzenji Yokochō", "Shinsekai / Tsūtenkaku for kushikatsu"],
    lastTrainBack: "JR Special Rapid to Kyoto until ~23:40; Hankyu to Kawaramachi until ~00:00.",
  },
  {
    date: "2026-11-09",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Open day",
    notes: "A second pass at whatever earned it — Arashiyama foliage, Kinkaku-ji, a quiet temple, or nothing at all.",
  },
  {
    date: "2026-11-10",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Last Kyoto day",
    notes: "Favourites, last shopping, tax-free paperwork, repacking. Ship the big cases tomorrow morning. Book a farewell dinner — Pontochō or a counter place.",
  },
  {
    date: "2026-11-11",
    legId: "tokyo-2",
    hotelId: "hotel-section-l-2",
    journeyId: "j-kyoto-tokyo",
    title: "Back to Tokyo",
    notes: "Drop the big cases at a Yamato centre / konbini, Nozomi to Tokyo, check in near the monorail. Afternoon free for last-day Tokyo plans.",
  },
  {
    date: "2026-11-12",
    legId: "tokyo-2",
    hotelId: "hotel-section-l-2",
    title: "Last full day",
    notes: "Whatever Tokyo you missed the first time. Collect the shipped cases at the desk. Final dinner, pack tonight, check in online for the flight.",
  },
  {
    date: "2026-11-13",
    legId: "tokyo-2",
    hotelId: "hotel-section-l-2",
    journeyId: "j-departure",
    title: "Fly home",
    notes: "Check out ~07:15, monorail to Haneda for the 10:00 departure.",
  },
];
