import type { Day } from "@/core/types";
type DaySeed = Omit<Day, "id">;

/** checklist strings -> {id,text}; ids are list-local and stable. */
const cl = (...t: string[]) => t.map((text, i) => ({ id: `k${i}`, text }));

/**
 * 24 days. Anchored days (arrival, travel, day trips, departure) carry real
 * plans; open Kyoto days are lightly sketched and meant to be filled in on the
 * device. Day-trip logistics live on the DayTrip pages, linked via `dayTripId`.
 * `entries` is one flat, time-ordered list — the shape of the day (arrival /
 * travel / day-trip) is derived from its journey / day-trip links.
 */
export const days: DaySeed[] = [
  {
    date: "2026-10-21",
    city: "Tokyo",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    journeyId: "j-arrival",
    title: "Arrival",
    summary: "In via Beijing on the red-eye. Get connected, drop the bags, stay upright until a normal bedtime.",
    entries: [
      { time: "07:00", title: "Land at Haneda", note: "Off the Beijing flight. Pick up eSIM data / pocket wifi. Buy Suica or Welcome Suica at the machines.", placeId: "stn-hamamatsucho" },
      { time: "08:30", title: "Monorail to Hamamatsuchō", note: "~13 min from Haneda; short walk to Section L. Bags may not be ready for check-in — ask to store them." },
      { time: "12:00", title: "Slow lunch nearby, then a flat walk", note: "Daylight and movement beat the jet lag. Nothing that needs energy or a booking." },
      { time: "15:00", title: "Check in, unpack, shower", placeId: "hotel-section-l" },
      { time: "18:00", title: "Easy first dinner nearby", note: "Within a 10-minute walk — konbini run for breakfast supplies after." },
      { time: "20:30", title: "Early night", note: "You've been up all night — but try to hold out to ~21:30." },
    ],
    packingReminder: "Keep the day bag light for the whole Tokyo leg — laundry on ~day 4.",
    checklist: cl("Activate eSIM", "Top up Suica (¥3,000)", "Photograph passport + landing stamp"),
  },
  {
    date: "2026-10-22",
    city: "Tokyo",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "Old Tokyo",
    summary: "Asakusa and the low city — a gentle, walkable first full day.",
    entries: [
      { time: "08:30", title: "Sensō-ji before the crowds", placeId: "p-sensoji" },
      { title: "Kappabashi kitchen street, then the Sumida riverside" },
      { title: "Dinner in Asakusa or back near Hamamatsuchō" },
    ],
  },
  {
    date: "2026-10-23",
    city: "Tokyo",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "West side",
    summary: "Meiji Jingū, Harajuku, and whatever else the day wants.",
    entries: [
      { time: "09:00", title: "Meiji Jingū", placeId: "p-meiji" },
      { title: "Omotesandō → Shibuya", placeId: "p-shibuya" },
      { title: "Shimokitazawa for dinner and record shops", placeId: "p-shimokita" },
    ],
  },
  {
    date: "2026-10-24",
    city: "Tokyo",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "East side & coffee",
    summary: "Kiyosumi gardens, the coffee list, and a laundry run before the mountains.",
    entries: [
      { time: "10:00", title: "Kiyosumi Teien garden", placeId: "p-koffee-mameya" },
      { title: "Coffee crawl — Kiyosumi / Kuramae / Nakameguro", placeId: "p-nakameguro" },
      { title: "Laundry night — coin laundry near the hotel" },
    ],
    packingReminder: "Run a wash tonight so everything's dry before Kawaguchiko.",
  },
  {
    date: "2026-10-25",
    city: "Tokyo",
    legId: "tokyo-1",
    hotelId: "hotel-section-l",
    title: "Open day",
    summary: "Flex day — a museum, the backstreets, more coffee, or just wandering. Repack tonight.",
    entries: [
      { title: "Tokyo National Museum, Ueno", placeId: "p-tokyo-nat-museum" },
      { title: "Split the luggage", note: "Overnight bag for Kawaguchiko; everything else in the big cases for Yamato tomorrow." },
    ],
    checklist: cl("Repack: overnight bag vs big cases", "Fill in the Yamato slip (to ICY / Yamato centre, Kyoto)", "Confirm Fuji Excursion seats"),
  },
  {
    date: "2026-10-26",
    city: "Lake Kawaguchiko",
    legId: "kawaguchiko",
    hotelId: "hotel-yamitsuki",
    journeyId: "j-tokyo-kawaguchiko",
    title: "To the lake",
    summary: "Ship the big cases, then the Fuji Excursion to Kawaguchiko. Afternoon by the water.",
    entries: [
      { time: "08:00", title: "Hand the large cases to Yamato", note: "At the hotel or a nearby centre." },
      { time: "08:30", title: "Fuji Excursion from Shinjuku", placeId: "stn-shinjuku" },
      { time: "10:30", title: "Check in area / drop bags at Villa Yamitsuki", placeId: "hotel-yamitsuki" },
      { title: "Ōishi Park and the lakeshow path", placeId: "p-oishi-park" },
      { title: "Onsen, then dinner", note: "See the genkan / tatami etiquette card." },
    ],
    checklist: cl("Yamato tracking number saved", "Overnight bag only"),
  },
  {
    date: "2026-10-27",
    city: "Lake Kawaguchiko",
    legId: "kawaguchiko",
    hotelId: "hotel-yamitsuki",
    title: "Fuji day",
    summary: "Chūreitō pagoda at first light, the ropeway, and a slow lake loop.",
    entries: [
      { time: "06:30", title: "Chūreitō Pagoda for sunrise on Fuji", note: "Clearest air is early. ~400 steps up.", placeId: "p-chureito" },
      { title: "Mt Kachi Kachi ropeway + lakeside lunch", placeId: "p-kachi-kachi" },
      { title: "Last onsen; repack for Kyoto" },
    ],
  },
  {
    date: "2026-10-28",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    journeyId: "j-kawaguchiko-kyoto",
    title: "To Kyoto",
    summary: "Liner bus to Mishima, Hikari to Kyoto. Settle in, find the konbini, gentle evening.",
    entries: [
      { time: "09:40", title: "Mishima Liner bus from Kawaguchiko", placeId: "stn-kawaguchiko" },
      { time: "12:10", title: "Hikari: Mishima → Kyoto", placeId: "stn-mishima" },
      { time: "15:00", title: "Check in to ICY; confirm the luggage arrived", placeId: "hotel-icy" },
      { title: "Nishiki Market for dinner bits, or Pontochō", placeId: "p-nishiki" },
    ],
    checklist: cl("Big cases received / located", "Learn the walk to the nearest station", "Buy a Kyoto bus/subway IC top-up"),
  },
  {
    date: "2026-10-29",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-kyoto",
    title: "Southern Higashiyama",
    summary: "Kiyomizu-dera down through the Sannenzaka lanes to Gion. The classic Kyoto walk.",
  },
  {
    date: "2026-10-30",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Fushimi Inari & Tōfuku-ji",
    summary: "Torii gates before 8, then the maple ravine at Tōfuku-ji as it starts to turn.",
    entries: [
      { time: "07:30", title: "Fushimi Inari — up to the Yotsutsuji viewpoint", placeId: "p-fushimi-inari" },
      { title: "Tōfuku-ji Tsūten-bridge and gardens", placeId: "p-tofukuji" },
      { title: "Coffee at Weekenders, dinner downtown", placeId: "p-weekenders" },
    ],
  },
  {
    date: "2026-10-31",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-arashiyama",
    title: "Arashiyama",
    summary: "Bamboo grove at opening, Tenryū-ji garden, the Sagano train if seats are free.",
  },
  {
    date: "2026-11-01",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Central Kyoto",
    summary: "A slower city day — Nijō Castle, Nishiki, the coffee list, Pokémon Center at Takashimaya.",
    entries: [
      { title: "Nijō Castle", placeId: "p-nijo" },
      { title: "Nishiki Market + Teramachi arcades", placeId: "p-nishiki" },
    ],
  },
  {
    date: "2026-11-02",
    city: "Nara",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-nara",
    title: "Nara",
    summary: "Tōdai-ji's Great Buddha, the deer, Kasuga's lanterns, Isuien garden.",
  },
  {
    date: "2026-11-03",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Culture Day",
    summary: "National holiday — expect crowds at the big sights. Good day for a museum, the Kyoto Railway Museum, or the quieter west of the city.",
    entries: [
      { title: "Kyoto Railway Museum or the Manga Museum", note: "Indoor, holiday-proof." },
    ],
  },
  {
    date: "2026-11-04",
    city: "Uji",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-uji",
    title: "Uji",
    summary: "Byōdō-in's Phoenix Hall, the riverside, and the best matcha of the trip.",
  },
  {
    date: "2026-11-05",
    city: "Ohara",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-ohara",
    title: "Ōhara",
    summary: "Bus north to the moss gardens of Sanzen-in — foliage peaks here first.",
  },
  {
    date: "2026-11-06",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Northern Higashiyama",
    summary: "Ginkaku-ji, the Philosopher's Path, Eikan-dō for its famous maples — walk south all afternoon.",
    entries: [
      { title: "Ginkaku-ji", placeId: "p-ginkakuji" },
      { title: "Philosopher's Path", placeId: "p-philosophers" },
      { title: "Eikan-dō (Zenrin-ji)", placeId: "p-eikando" },
    ],
  },
  {
    date: "2026-11-07",
    city: "Kurama & Kibune",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-kurama",
    title: "Kurama → Kibune",
    summary: "The little mountain railway, the temple-to-shrine hike over the ridge, kaiseki by the river.",
  },
  {
    date: "2026-11-08",
    city: "Osaka",
    legId: "kyoto",
    hotelId: "hotel-icy",
    dayTripId: "dt-osaka",
    title: "Osaka",
    summary: "Kuromon market, the castle, Dōtonbori after dark. Loud, fun, a change of pace.",
  },
  {
    date: "2026-11-09",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Open day",
    summary: "A second pass at whatever earned it — Arashiyama foliage, Kinkaku-ji, a quiet temple, or nothing at all.",
  },
  {
    date: "2026-11-10",
    city: "Kyoto",
    legId: "kyoto",
    hotelId: "hotel-icy",
    title: "Last Kyoto day",
    summary: "Favourites, last shopping, tax-free paperwork, and repacking. Ship the big cases tomorrow morning.",
    entries: [
      { title: "Farewell dinner", note: "Book something — Pontochō or a counter place." },
    ],
    checklist: cl("Tax-free receipts together with passports", "Repack; big cases ready for Yamato", "Fill in the Kyoto → Tokyo Yamato slip"),
  },
  {
    date: "2026-11-11",
    city: "Tokyo",
    legId: "tokyo-2",
    hotelId: "hotel-section-l-2",
    journeyId: "j-kyoto-tokyo",
    title: "Back to Tokyo",
    summary: "Ship the cases, Nozomi to Tokyo, check in near the monorail. Afternoon free.",
    entries: [
      { time: "08:30", title: "Drop big cases at a Yamato centre / konbini", placeId: "hotel-icy" },
      { time: "10:30", title: "Nozomi: Kyoto → Tokyo", placeId: "stn-kyoto" },
      { title: "Check in at Section L, then last-day Tokyo plans", placeId: "hotel-section-l-2" },
    ],
  },
  {
    date: "2026-11-12",
    city: "Tokyo",
    legId: "tokyo-2",
    hotelId: "hotel-section-l-2",
    title: "Last full day",
    summary: "Whatever Tokyo you missed the first time. Collect the shipped cases at the desk. Pack tonight.",
    entries: [
      { title: "Final dinner; early-ish night before the flight" },
    ],
    checklist: cl("Confirm big cases arrived at the desk", "Check in online for the flight", "Spend or change leftover coins"),
  },
  {
    date: "2026-11-13",
    city: "Tokyo",
    legId: "tokyo-2",
    hotelId: "hotel-section-l-2",
    journeyId: "j-departure",
    title: "Fly home",
    summary: "Monorail to Haneda for the 10:00 departure.",
    entries: [
      { time: "07:15", title: "Check out", placeId: "hotel-section-l-2" },
      { time: "07:30", title: "Monorail to Haneda", placeId: "stn-hamamatsucho" },
      { time: "10:00", title: "Flight home" },
    ],
  },
];
