import type { Hotel } from "@/core/types";

/**
 * Detail records. Addresses, door codes, wifi and reservation refs are
 * placeholders — fill them in on the device. `nearby` is seeded with the useful
 * categories; every row opens straight into Google Maps.
 */
export const hotels: Hotel[] = [
  {
    id: "hotel-section-l",
    placeId: "hotel-section-l",
    name: "Section L Hamamatsuchō",
    address: "Hamamatsuchō, Minato-ku, Tokyo — full address to add",
    phone: "",
    url: "",
    checkIn: "16:00",
    checkOut: "10:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    gallery: ["hotel-section-l"],
    access: {
      stationWalkMin: 6,
      grade: "flat",
      elevator: true,
      note: "Hamamatsuchō (JR Yamanote / Keihin-Tōhoku) and the Haneda monorail terminal; Daimon (Toei) is closer to some units.",
    },
    nearby: [
      { type: "station", name: "Hamamatsuchō Station", walkMin: 6, gmapsQuery: "Hamamatsucho Station", note: "JR + Tokyo Monorail to Haneda" },
      { type: "station", name: "Daimon Station", walkMin: 4, gmapsQuery: "Daimon Station Tokyo", note: "Toei Asakusa / Oedo lines" },
      { type: "convenience", brand: "7-Eleven", name: "7-Eleven (nearest)", walkMin: 2, gmapsQuery: "7-Eleven Hamamatsucho" },
      { type: "convenience", brand: "Lawson", name: "Lawson (nearest)", walkMin: 3, gmapsQuery: "Lawson Hamamatsucho" },
      { type: "convenience", brand: "FamilyMart", name: "FamilyMart (nearest)", walkMin: 3, gmapsQuery: "FamilyMart Hamamatsucho" },
      { type: "supermarket", name: "Supermarket (nearest)", walkMin: 7, gmapsQuery: "supermarket Hamamatsucho" },
      { type: "pharmacy", name: "Pharmacy / drugstore", walkMin: 5, gmapsQuery: "drugstore Hamamatsucho" },
      { type: "atm", name: "7-Bank ATM (accepts foreign cards)", walkMin: 2, gmapsQuery: "7 Bank ATM Hamamatsucho" },
      { type: "courier", brand: "Yamato (Kuroneko)", name: "Yamato Transport service centre", walkMin: 8, gmapsQuery: "Yamato Transport Minato Hamamatsucho" },
      { type: "laundry", name: "Coin laundry", walkMin: 9, gmapsQuery: "coin laundry Hamamatsucho" },
    ],
    notes: "First stay: 5 nights, 21–26 Oct. Ship the large cases from here to Kyoto on the 26th (or via the front desk the evening before).",
  },
  {
    id: "hotel-section-l-2",
    placeId: "hotel-section-l-2",
    name: "Section L Hamamatsuchō — return",
    address: "Hamamatsuchō, Minato-ku, Tokyo — full address to add",
    checkIn: "16:00",
    checkOut: "10:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    gallery: ["hotel-section-l"],
    access: {
      stationWalkMin: 6,
      grade: "flat",
      elevator: true,
      note: "Same area as the first stay — handy for the monorail to Haneda on departure morning.",
    },
    nearby: [
      { type: "station", name: "Hamamatsuchō Station", walkMin: 6, gmapsQuery: "Hamamatsucho Station", note: "Monorail to Haneda, ~13 min" },
      { type: "convenience", brand: "7-Eleven", name: "7-Eleven (nearest)", walkMin: 2, gmapsQuery: "7-Eleven Hamamatsucho" },
      { type: "atm", name: "7-Bank ATM", walkMin: 2, gmapsQuery: "7 Bank ATM Hamamatsucho" },
      { type: "courier", brand: "Yamato (Kuroneko)", name: "Yamato Transport service centre", walkMin: 8, gmapsQuery: "Yamato Transport Minato Hamamatsucho" },
    ],
    notes: "Second stay: 2 nights, 11–13 Nov. Flight home 13 Nov, 10:00 — leave by ~07:30.",
  },
  {
    id: "hotel-yamitsuki",
    placeId: "hotel-yamitsuki",
    name: "Villa Yamitsuki",
    address: "Kawaguchiko, Fujikawaguchiko, Yamanashi — full address to add",
    checkIn: "15:00",
    checkOut: "10:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    gallery: ["hotel-yamitsuki"],
    access: {
      stationWalkMin: 15,
      grade: "gentle",
      elevator: false,
      note: "Around the lake from Kawaguchiko Station — a taxi or the Retro Bus is easiest with bags. Confirm parking / pickup with the host.",
    },
    nearby: [
      { type: "station", name: "Kawaguchiko Station", walkMin: 15, gmapsQuery: "Kawaguchiko Station", note: "Fujikyu line + bus terminal; Retro Bus loops the lake" },
      { type: "convenience", brand: "Lawson", name: "Lawson (nearest)", walkMin: 8, gmapsQuery: "Lawson Kawaguchiko" },
      { type: "supermarket", name: "Supermarket (Max Valu / Ogino)", walkMin: 12, gmapsQuery: "supermarket Kawaguchiko" },
      { type: "convenience", brand: "7-Eleven", name: "7-Eleven", walkMin: 10, gmapsQuery: "7-Eleven Kawaguchiko" },
      { type: "atm", name: "Post office / 7-Bank ATM", walkMin: 12, gmapsQuery: "7 Bank ATM Kawaguchiko" },
      { type: "courier", brand: "Yamato (Kuroneko)", name: "Yamato Transport (Fujikawaguchiko)", walkMin: 14, gmapsQuery: "Yamato Transport Fujikawaguchiko" },
    ],
    notes: "2 nights, 26–28 Oct. This is the ryokan-style stay — see the genkan / tatami etiquette card. Onsen towel and slippers provided.",
  },
  {
    id: "hotel-icy",
    placeId: "hotel-icy",
    name: "ICY (Airbnb)",
    address: "Kyoto — full address to add from the booking",
    checkIn: "15:00",
    checkOut: "11:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    gallery: ["hotel-icy"],
    access: {
      stationWalkMin: 8,
      grade: "flat",
      elevator: false,
      note: "Confirm the exact nearest subway/bus stop and the self-check-in steps with the host before arrival.",
    },
    nearby: [
      { type: "station", name: "Nearest subway / bus stop", walkMin: 8, gmapsQuery: "Kyoto subway station", note: "To confirm with host" },
      { type: "convenience", brand: "Lawson", name: "Lawson (nearest)", walkMin: 3, gmapsQuery: "Lawson Kyoto" },
      { type: "convenience", brand: "FamilyMart", name: "FamilyMart (nearest)", walkMin: 4, gmapsQuery: "FamilyMart Kyoto" },
      { type: "supermarket", name: "Fresco / Life supermarket", walkMin: 6, gmapsQuery: "Fresco supermarket Kyoto" },
      { type: "pharmacy", name: "Matsumoto Kiyoshi / drugstore", walkMin: 6, gmapsQuery: "drugstore Kyoto" },
      { type: "atm", name: "7-Bank ATM", walkMin: 3, gmapsQuery: "7 Bank ATM Kyoto" },
      { type: "courier", brand: "Yamato (Kuroneko)", name: "Yamato Transport service centre", walkMin: 10, gmapsQuery: "Yamato Transport Kyoto" },
      { type: "laundry", name: "Coin laundry", walkMin: 7, gmapsQuery: "coin laundry Kyoto" },
    ],
    notes: "14 nights, 28 Oct – 11 Nov. The big cases should be waiting here on the 28th. Base for all the day trips.",
  },
];
