import type { Hotel } from "@/core/types";

/** Detail records. Addresses, door codes, wifi and refs are placeholders —
 *  fill them in from the bookings. */
export const hotels: Hotel[] = [
  {
    id: "hotel-section-l",
    name: "Section L Hamamatsuchō",
    address: "Hamamatsuchō, Minato-ku, Tokyo — full address to add",
    addressJp: "",
    directions: "~6 min flat walk from Hamamatsuchō (JR Yamanote / Keihin-Tōhoku, and the Haneda monorail). Daimon (Toei) is closer to some units.",
    mapUrl: "",
    checkIn: "16:00",
    checkOut: "10:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    notes: "First stay: 5 nights, 21–26 Oct. Ship the large cases from here to Kyoto on the 26th (or via the front desk the evening before).",
  },
  {
    id: "hotel-yamitsuki",
    name: "Villa Yamitsuki",
    address: "Kawaguchiko, Fujikawaguchiko, Yamanashi — full address to add",
    addressJp: "",
    directions: "Around the lake from Kawaguchiko Station (~15 min) — a taxi or the Retro Bus is easiest with bags. Confirm parking / pickup with the host.",
    mapUrl: "",
    checkIn: "15:00",
    checkOut: "10:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    notes: "2 nights, 26–28 Oct. The ryokan-style stay — genkan / tatami: shoes off at the entrance. Onsen towel and slippers provided.",
  },
  {
    id: "hotel-icy",
    name: "ICY (Airbnb)",
    address: "Kyoto — full address to add from the booking",
    addressJp: "",
    directions: "Confirm the exact nearest subway/bus stop and the self-check-in steps with the host before arrival (~8 min flat walk).",
    mapUrl: "",
    checkIn: "15:00",
    checkOut: "11:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    notes: "14 nights, 28 Oct – 11 Nov. The big cases should be waiting here on the 28th — no staffed desk, so arrange delivery/collection with the host. Base for all the day trips.",
  },
  {
    id: "hotel-section-l-2",
    name: "Section L Hamamatsuchō — return",
    address: "Hamamatsuchō, Minato-ku, Tokyo — full address to add",
    addressJp: "",
    directions: "Same area as the first stay — handy for the monorail to Haneda (~13 min) on departure morning.",
    mapUrl: "",
    checkIn: "16:00",
    checkOut: "10:00",
    wifi: "",
    doorCode: "",
    reservationRef: "",
    notes: "Second stay: 2 nights, 11–13 Nov. Flight home 13 Nov, 10:00 — leave by ~07:30. The desk here will hold the shipped cases.",
  },
];
